<?php

namespace ContainerT7kjf83;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeYYwCfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EeYYwCf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EeYYwCf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArticleController::createArticle' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ArticleController::listAllActiveArticles' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController::listAllArticles' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController::listAllArticlesAdditional' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController::showArticleCSV' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ArticleController:createArticle' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ArticleController:listAllActiveArticles' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController:listAllArticles' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController:listAllArticlesAdditional' => ['privates', '.service_locator.7gcTQjE', 'get_ServiceLocator_7gcTQjEService', true],
            'App\\Controller\\ArticleController:showArticleCSV' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ArticleController::createArticle' => '?',
            'App\\Controller\\ArticleController::listAllActiveArticles' => '?',
            'App\\Controller\\ArticleController::listAllArticles' => '?',
            'App\\Controller\\ArticleController::listAllArticlesAdditional' => '?',
            'App\\Controller\\ArticleController::showArticleCSV' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ArticleController:createArticle' => '?',
            'App\\Controller\\ArticleController:listAllActiveArticles' => '?',
            'App\\Controller\\ArticleController:listAllArticles' => '?',
            'App\\Controller\\ArticleController:listAllArticlesAdditional' => '?',
            'App\\Controller\\ArticleController:showArticleCSV' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
