<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT7kjf83\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT7kjf83/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT7kjf83.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT7kjf83\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT7kjf83\App_KernelDevDebugContainer([
    'container.build_hash' => 'T7kjf83',
    'container.build_id' => 'c89f9413',
    'container.build_time' => 1682867258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT7kjf83');
